name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - master  # Or use main if that's your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js (ensure compatibility with Angular CLI)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the Angular app
      - name: Build the Angular app
        run: npm run build --prod

      # List files in dist/flipbook (verify correct path)
      - name: List contents of dist/flipbook
        run: ls -l dist/flipbook

      # Check if the dist/flipbook/browser folder exists
      - name: Check contents of dist/flipbook/
        run: ls -l dist/flipbook/

      # Set git config user
      - name: Set git config user
        run: |
          git config --global user.email "mobsled@pm.me"
          git config --global user.name "Martin Gajdos"

      # Configure GitHub authentication with PAT
      - name: Configure GitHub authentication
        run: |
          git config --global url."https://${{ secrets.MY_GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        run: |
          npx angular-cli-ghpages --dir=dist/flipbook --no-silent
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
